### PR TITLE
fixed

### PR DESCRIPTION
**Pull request by aniruddhajoshi100**

### CODE REVIEW

**Comment by aniruddhajoshi100** [comment]
fixed collision issue, issue #3

**Comment by Vaarun-C** [comment]
image
some small issue at the top and bottom borders other than that its great!!! :) please try to fix this small bug

**Comment by aniruddhajoshi100** [comment]
okay, working on it

**Comment by aniruddhajoshi100** [comment]
I think I got it, can u check?

**Comment by aniruddhajoshi100** [comment]
added 2nd commit by accident, pls ignore that

**Comment by Vaarun-C** [comment]
!bounty 25

**Pull request merged**
