### PR TITLE
updated code

### PR DESCRIPTION
**Pull request by atharvakinage**
issue 1
added volume slider to box.py

### CODE REVIEW

**Comment by Vaarun-C** [comment]
The slider is not ideal 
image
Please fix this issue 
The slider doesn't seem to work properly

**Comment by atharvakinage** [comment]
ok ill try doing it 
give me 10 mins

**Comment by Vaarun-C** [comment]
Sure :)

**Comment by atharvakinage** [comment]
can you check the updated code once

**Comment by Vaarun-C** [comment]
Ideally, I want the trailing boxes to be there. Also the slider is not draggable @atharvakinage

**Comment by atharvakinage** [comment]
fixed the draggable slider ...but im not able to get the trailing boxes :(

**Comment by Vaarun-C** [comment]
Can you try fixing it?

**Comment by atharvakinage** [comment]
yes i will

**Comment by atharvakinage** [comment]
can you check this now
it looks fine

**Comment by Vaarun-C** [comment]
Hey theres still a lot of issues with the code:
- The colour for each box remains the same now. But each box must be of different colours
- The slider disappears if I drag it our of bounds.

**Comment by atharvakinage** [comment]
can you check it now

**Comment by Vaarun-C** [comment]
Hey! Your PR seems to affect other parts of the codebase.
Could you please resolve this, inorder to be accepted

**Comment by Vaarun-C** [comment]
If you are unwilling to do this just inform me so that I can reassign this issue

**Comment by atharvakinage** [comment]
umm fine ....you can reassign this

**Comment by Vaarun-C** [comment]
cool

**Pull request closed without merging**
